# add your custom package feeds here
#
# src/gz example_feed_name http://www.example.com/path/to/files
src/gz dolphin738_packages https://github.com/dolphin738/op-packages.git
src/gz OpenAppFilter https://github.com/destan19/OpenAppFilter.git
src/gz rtp2httpd https://github.com/stackia/rtp2httpd.git
