# add your custom package feeds here
#
# src/gz example_feed_name http://www.example.com/path/to/files
src/gz kwrt_core https://dl.openwrt.ai/releases/25.12/targets/qualcommax/ipq60xx/6.12.74/
src/gz kwrt_base https://dl.openwrt.ai/releases/25.12/packages/aarch64_cortex-a53/base/
src/gz kwrt_packages https://dl.openwrt.ai/releases/25.12/packages/aarch64_cortex-a53/packages/
src/gz kwrt_luci https://dl.openwrt.ai/releases/25.12/packages/aarch64_cortex-a53/luci/
src/gz kwrt_routing https://dl.openwrt.ai/releases/25.12/packages/aarch64_cortex-a53/routing/
src/gz kwrt_kiddin9 https://dl.openwrt.ai/releases/25.12/packages/aarch64_cortex-a53/kiddin9/
